/**
 * Debug Panel Milestones Key Matching
 *
 * This script checks if the keys generated by the vacuum parser match
 * the keys used by the CrossRef input builder.
 *
 * Usage:
 *   npx tsx tools/dev/debugPanelMilestonesKeys.ts "path/to/SimulationStatus.xlsx"
 */

import XLSX from 'xlsx'
import fs from 'fs'
import path from 'path'

import { sheetToMatrix, findHeaderRow } from '../../src/ingestion/excelUtils'
import {
  vacuumParseSimulationSheet,
  convertVacuumRowsToPanelMilestones,
  parseSimulationStatus,
} from '../../src/ingestion/simulationStatusParser'
import { normalizeStationId } from '../../src/domain/crossRef/CrossRefUtils'

const REQUIRED_HEADERS = ['STATION', 'ROBOT']

async function main(): Promise<void> {
  const filePath = process.argv[2]

  if (!filePath) {
    console.error('Usage: npx tsx tools/dev/debugPanelMilestonesKeys.ts "path/to/file.xlsx"')
    process.exit(1)
  }

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`)
    process.exit(1)
  }

  const fileName = path.basename(filePath)
  console.log('=' .repeat(80))
  console.log('DEBUG: Panel Milestones Key Matching')
  console.log('=' .repeat(80))
  console.log(`File: ${fileName}`)

  const workbook = XLSX.readFile(filePath)

  // STEP 1: Get vacuum rows and build panel milestones map
  console.log('\n--- STEP 1: Vacuum Parser Keys ---')

  const simulationSheets = ['SIMULATION', 'MRS_OLP', 'DOCUMENTATION', 'SAFETY_LAYOUT']
  const allVacuumRows: any[] = []

  for (const sheetName of simulationSheets) {
    if (!workbook.SheetNames.includes(sheetName)) continue

    const rows = sheetToMatrix(workbook, sheetName)
    const headerRowIndex = findHeaderRow(rows, REQUIRED_HEADERS)
    if (headerRowIndex === null) continue

    const { rows: vacuumRows } = vacuumParseSimulationSheet(
      rows,
      headerRowIndex,
      fileName,
      sheetName
    )
    allVacuumRows.push(...vacuumRows)
  }

  const panelMilestonesMap = convertVacuumRowsToPanelMilestones(allVacuumRows)

  console.log(`Total vacuum rows: ${allVacuumRows.length}`)
  console.log(`Panel milestones map size: ${panelMilestonesMap.size}`)

  // Show all station-level keys
  const stationKeys = [...panelMilestonesMap.keys()].filter(k => !k.includes('::'))
  const robotKeys = [...panelMilestonesMap.keys()].filter(k => k.includes('::'))

  console.log(`\nStation-level keys (${stationKeys.length}):`)
  stationKeys.forEach(k => console.log(`  "${k}"`))

  console.log(`\nRobot-level keys (first 10 of ${robotKeys.length}):`)
  robotKeys.slice(0, 10).forEach(k => console.log(`  "${k}"`))

  // STEP 2: Parse using the main parseSimulationStatus function to get cells
  console.log('\n--- STEP 2: Cell.code values from parseSimulationStatus ---')

  const parseResult = await parseSimulationStatus(workbook, fileName)

  console.log(`Cells created: ${parseResult.cells.length}`)
  console.log(`\nCell.code values:`)
  parseResult.cells.forEach(cell => {
    console.log(`  Cell ID: "${cell.id}", code: "${cell.code}", name: "${cell.name}"`)
  })

  // STEP 3: Check if cell.code values match panel milestones keys
  console.log('\n--- STEP 3: Key Matching Analysis (Direct) ---')

  let matchCount = 0
  let missCount = 0

  for (const cell of parseResult.cells) {
    const hasMatch = panelMilestonesMap.has(cell.code)
    if (hasMatch) {
      matchCount++
      console.log(`  ✓ "${cell.code}" FOUND in panel milestones map`)
    } else {
      missCount++
      console.log(`  ✗ "${cell.code}" NOT FOUND in panel milestones map`)

      // Try to find similar keys
      const similarKeys = [...panelMilestonesMap.keys()].filter(k =>
        k.includes(cell.code) || cell.code.includes(k)
      )
      if (similarKeys.length > 0) {
        console.log(`    Possible similar keys: ${similarKeys.slice(0, 3).join(', ')}`)
      }
    }
  }

  console.log('\n--- STEP 3b: Key Matching Analysis (After normalizeStationId) ---')
  console.log('This simulates what happens in CrossRefEngine.attachSimulationStatus()')

  let normalizedMatchCount = 0
  let normalizedMissCount = 0

  for (const cell of parseResult.cells) {
    const normalizedKey = normalizeStationId(cell.code)
    const hasMatch = panelMilestonesMap.has(normalizedKey)

    console.log(`  "${cell.code}" → normalized: "${normalizedKey}" → ${hasMatch ? 'FOUND' : 'NOT FOUND'}`)

    if (hasMatch) {
      normalizedMatchCount++
    } else {
      normalizedMissCount++
    }
  }

  console.log('\n--- SUMMARY ---')
  console.log(`Direct match: ${matchCount}/${parseResult.cells.length}`)
  console.log(`After normalization: ${normalizedMatchCount}/${parseResult.cells.length}`)
  console.log(`Missing after normalization: ${normalizedMissCount}/${parseResult.cells.length}`)

  if (missCount > 0) {
    console.log('\n⚠️  KEY MISMATCH DETECTED!')
    console.log('The cell.code values do not match the panel milestones map keys.')
    console.log('This is why panel milestones are not being attached to cells.')
  }
}

main().catch(err => {
  console.error('Error:', err)
  process.exit(1)
})
