import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { PageHeader } from '../../ui/components/PageHeader'
import { coreStore } from '../../domain/coreStore'
import { createAliasRule } from '../../ingestion/uidResolver'
import type { DiffAmbiguous } from '../../domain/uidTypes'

interface AmbiguityBundle {
  fileName: string
  filePath: string
  ambiguousItems: DiffAmbiguous[]
  totalAmbiguous: number
}

export default function AmbiguityBundleImportPage() {
  const [bundle, setBundle] = useState<AmbiguityBundle | null>(null)
  const [resolving, setResolving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const navigate = useNavigate()

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    try {
      const text = await file.text()
      const parsed = JSON.parse(text) as AmbiguityBundle

      // Validate structure
      if (!parsed.ambiguousItems || !Array.isArray(parsed.ambiguousItems)) {
        throw new Error('Invalid bundle format: missing ambiguousItems array')
      }

      setBundle(parsed)
      setError(null)
    } catch (err) {
      setError(`Failed to load bundle: ${String(err)}`)
      setBundle(null)
    }
  }

  const handleLinkToCandidate = (ambiguousKey: string, candidateUid: string, entityType: string) => {
    setResolving(true)

    const rule = createAliasRule(
      ambiguousKey,
      candidateUid,
      entityType as any,
      `User linked ${ambiguousKey} to ${candidateUid} via Ambiguity Bundle Import`,
      'local-user'
    )

    coreStore.createAliasRule(rule)

    // Remove this ambiguous item from the bundle
    if (bundle) {
      const updatedItems = bundle.ambiguousItems.filter(a => a.newKey !== ambiguousKey)
      setBundle({
        ...bundle,
        ambiguousItems: updatedItems,
        totalAmbiguous: updatedItems.length
      })
    }

    setResolving(false)
  }

  const handleCreateNew = (ambiguousKey: string) => {
    setResolving(true)

    // Simply remove from ambiguous list - will be created as new entity
    if (bundle) {
      const updatedItems = bundle.ambiguousItems.filter(a => a.newKey !== ambiguousKey)
      setBundle({
        ...bundle,
        ambiguousItems: updatedItems,
        totalAmbiguous: updatedItems.length
      })
    }

    setResolving(false)
  }

  if (!bundle) {
    return (
      <div className="p-6 space-y-6">
        <PageHeader
          title="Import Ambiguity Bundle"
          subtitle="Load ambiguity JSON from regression harness and resolve conflicts"
        />

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-4">
            Select Ambiguity Bundle
          </h3>

          <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Load a <code className="bg-gray-100 dark:bg-gray-900 px-1 rounded">*_ambiguity.json</code> file generated by the regression harness.
          </p>

          <div className="space-y-4">
            <input
              type="file"
              accept=".json"
              onChange={handleFileSelect}
              className="block w-full text-sm text-gray-900 dark:text-gray-100
                file:mr-4 file:py-2 file:px-4
                file:rounded file:border-0
                file:text-sm file:font-medium
                file:bg-blue-50 file:text-blue-700
                hover:file:bg-blue-100
                dark:file:bg-blue-900/30 dark:file:text-blue-400
                dark:hover:file:bg-blue-900/50"
            />

            {error && (
              <div className="bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-800 rounded p-3">
                <p className="text-sm text-red-800 dark:text-red-400">{error}</p>
              </div>
            )}
          </div>

          <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/10 border border-blue-200 dark:border-blue-800 rounded">
            <h4 className="text-sm font-medium text-blue-900 dark:text-blue-400 mb-2">
              Workflow
            </h4>
            <ol className="text-sm text-blue-800 dark:text-blue-300 space-y-1 list-decimal list-inside">
              <li>Run regression harness with --uid --mutate-names flags</li>
              <li>Locate ambiguity bundle in <code className="bg-blue-100 dark:bg-blue-900/50 px-1 rounded">artifacts/real-data-regress/[timestamp]/ambiguity/</code></li>
              <li>Import bundle JSON here</li>
              <li>Resolve ambiguities by linking to existing entities or creating new ones</li>
              <li>Alias rules are saved to the registry for future imports</li>
            </ol>
          </div>
        </div>

        <button
          onClick={() => navigate('/import-history')}
          className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100 rounded hover:bg-gray-300 dark:hover:bg-gray-600"
        >
          Back to Import History
        </button>
      </div>
    )
  }

  if (bundle.ambiguousItems.length === 0) {
    return (
      <div className="p-6 space-y-6">
        <PageHeader title="Ambiguity Bundle" subtitle="All conflicts resolved" />

        <div className="bg-green-50 dark:bg-green-900/10 border border-green-200 dark:border-green-800 rounded-lg p-6">
          <h3 className="text-lg font-medium text-green-900 dark:text-green-400 mb-2">
            ✓ Complete
          </h3>
          <p className="text-sm text-green-800 dark:text-green-300">
            All ambiguous items from <strong>{bundle.fileName}</strong> have been resolved.
          </p>
        </div>

        <div className="flex gap-2">
          <button
            onClick={() => setBundle(null)}
            className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
          >
            Load Another Bundle
          </button>
          <button
            onClick={() => navigate('/registry')}
            className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100 rounded hover:bg-gray-300 dark:hover:bg-gray-600"
          >
            View Registry
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Resolve Ambiguities"
        subtitle={`${bundle.fileName} - ${bundle.ambiguousItems.length} ambiguous items`}
      />

      <div className="bg-yellow-50 dark:bg-yellow-900/10 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
        <p className="text-sm text-yellow-800 dark:text-yellow-400">
          <strong>No silent guessing:</strong> The following items have multiple possible matches.
          You must decide whether to link to an existing entity or create a new one.
        </p>
      </div>

      <div className="space-y-4">
        {bundle.ambiguousItems.map((item, idx) => (
          <div key={idx} className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                {item.newKey}
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                {item.entityType} • Plant: {item.plantKey}
              </p>
            </div>

            <div className="mb-4">
              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Possible matches ({item.candidates.length}):
              </h4>
              <div className="space-y-2">
                {item.candidates.map((candidate, cidx) => (
                  <div
                    key={cidx}
                    className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-900/50 rounded border border-gray-200 dark:border-gray-700"
                  >
                    <div className="flex-1">
                      <p className="font-mono text-sm text-gray-900 dark:text-gray-100">
                        {candidate.key}
                      </p>
                      <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                        Score: {candidate.matchScore} • {candidate.reasons.join(', ')}
                      </p>
                    </div>
                    <button
                      onClick={() => handleLinkToCandidate(item.newKey, candidate.uid, item.entityType)}
                      disabled={resolving}
                      className="ml-4 px-3 py-1 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 disabled:opacity-50"
                    >
                      Link to this
                    </button>
                  </div>
                ))}
              </div>
            </div>

            <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
              <button
                onClick={() => handleCreateNew(item.newKey)}
                disabled={resolving}
                className="px-4 py-2 bg-green-600 text-white text-sm rounded hover:bg-green-700 disabled:opacity-50"
              >
                Create as new entity
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="flex gap-2">
        <button
          onClick={() => setBundle(null)}
          className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100 rounded hover:bg-gray-300 dark:hover:bg-gray-600"
        >
          Load Different Bundle
        </button>
        <button
          onClick={() => navigate('/import-history')}
          className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-100 rounded hover:bg-gray-300 dark:hover:bg-gray-600"
        >
          Back to Import History
        </button>
      </div>
    </div>
  )
}
